# Generated by Django 5.2.8 on 2025-12-01 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Offered price')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('KRW', 'Korean Won'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen')], default='USD', max_length=3, verbose_name='Currency')),
                ('message', models.TextField(blank=True, help_text='Optional message from buyer', verbose_name='Message to producer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('validity_days', models.PositiveIntegerField(default=7, help_text='Number of days this offer is valid', verbose_name='Validity (days)')),
                ('expires_at', models.DateTimeField(help_text='Calculated expiry date', verbose_name='Expires at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded at')),
                ('producer_response', models.TextField(blank=True, help_text='Optional message from producer', verbose_name='Producer response')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('buyer', models.ForeignKey(limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_offers', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_set', to='contents.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', 'status'], name='offers_offe_buyer_i_75fdfb_idx'), models.Index(fields=['content', 'status'], name='offers_offe_content_87cb38_idx'), models.Index(fields=['status', 'expires_at'], name='offers_offe_status_f98e70_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('content', 'buyer'), name='unique_pending_offer_per_content_buyer')],
            },
        ),
    ]
