# Generated by Django 5.2.8 on 2025-12-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offer',
            name='unique_pending_offer_per_content_buyer',
        ),
    ]
