# Generated by Django 5.2.8 on 2025-12-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='content',
            name='poster',
            field=models.ImageField(blank=True, help_text='Vertical poster image for content', null=True, upload_to='posters/', verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='content',
            name='rating',
            field=models.CharField(choices=[('all', 'All ages'), ('12', '12+'), ('15', '15+'), ('19', '19+')], default='all', help_text='Content age restriction', max_length=3, verbose_name='Age rating'),
        ),
        migrations.AddField(
            model_name='content',
            name='release_target',
            field=models.DateField(blank=True, help_text='Desired release date for the content', null=True, verbose_name='Target release date'),
        ),
        migrations.AddField(
            model_name='content',
            name='screener_url',
            field=models.URLField(blank=True, help_text='Internal screener video with watermark', max_length=500, verbose_name='Screener URL'),
        ),
    ]
